Add documentation for dbUrl* options.
I encountered this error while attempting to use `--adminPassword`:

```
Error: Authentication credentials (username AND password) are missing from dbUrl. Provide them either by --dbUrl directly or by setting --dbUrlUsername and --dbUrlPassword arguments.
```

Since I couldn't find documentation elsewhere on `dbUrlUsername` and `dbUrlPassword`, so I added some.